name: Validate Terraform

on:
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    environment: BLG2CODEDEV
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
      - name: Terraform init
        run: terraform -chdir=infra/terraform init -backend=false
      - name: Terraform validate
        run: terraform -chdir=infra/terraform validate
